# Generated by Django 3.2.6 on 2021-08-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='customer')),
                ('item', models.CharField(max_length=255, verbose_name='item')),
                ('total', models.PositiveIntegerField(verbose_name='total')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
