# Generated by Django 3.2.6 on 2021-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='customer',
        ),
        migrations.AddField(
            model_name='deal',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
